version: '3'

services:

  db:
    image: postgres
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=1234
    ports:
      - "5432:5432"
    networks:
      - node-network

  back-end:
    build:
      context: server
    container_name: back-end
    working_dir: /usr/src/app
    networks:
      - node-network
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    tty: true
    ports:
      - "4000:4000"
    command: npm run start
    depends_on:
      - db

  front-end:
    stdin_open: true
    build:
      context: client
    container_name: front-end
    working_dir: /app
    networks:
      - node-network
    volumes:
      - ./client:/app
      - /app/node_modules

  nginx:
    build:
      context: nginx
    container_name: nginx
    restart: always
    tty: true
    ports:
      - "8000:80"
    networks:
      - node-network
    depends_on:
      - back-end
      - front-end

networks:
  node-network:
    driver: bridge
